[package]
name = "take-api"
version = "0.1.0"
authors = ["William D. Jones <thor0505@comcast.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.msp430]
version = "0.1.0"

[dependencies.msp430-rt]
version = "0.2.0"

# [dependencies.msp430-rtfm]
# git = "https://github.com/japaric/msp430-rtfm"

[dependencies.msp430g2553]
features = ["rt"]
version = "0.2.0"

[dependencies.panic-msp430]
version = "0.1.0"

[dev-dependencies]
# bare-metal = "0.2.5"
my-wrapper = { path = "../my-wrapper" }

[features]
unsafe = []
trigger-regress = []
