[package]
name = "take-api"
version = "0.1.0"
authors = ["William D. Jones <thor0505@comcast.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
msp430 = "0.3.0" # Version may need to be specified to avoid llvm_asm! issues.
msp430-rt = "0.3.0"
panic-msp430 = "0.3.0"


# [dependencies.msp430-rtfm]
# git = "https://github.com/japaric/msp430-rtfm"

[dependencies.msp430g2553]
features = ["rt"]
version = "0.3.0"

[dev-dependencies]
bare-metal = "1.0.0"
once_cell = { version = "1.7.0", default_features = false}

[features]
unsafe = []
use-bare-metal = []
