[workspace]
members = ["my-wrapper", "borrow-api", "take-api"]

[patch.crates-io.msp430g2553]
git = "https://github.com/cr1901/msp430g2553"
branch = "rt-up"

[profile.release]
opt-level = "s"
lto = true
